import { StyleSheet } from "react-native";

export const shapeGameStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F9FAFB",
    alignItems: "center",
    // justifyContent: "center",
    paddingHorizontal: 20,
    // paddingVertical: 80,
    paddingVertical: 55,
  },
  textHeader: {
    marginHorizontal: 10,
    marginVertical: 35,
  },
  headerText: {
    fontSize: 25,
    fontWeight: "bold",
    color: "#0c0596ff",
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: "90%",
    marginTop: 60,
    marginBottom: 30,
  },
  backButton: {
    backgroundColor: "#c3f3daff",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
  },
  backButtonText: {
    color: "#047857",
    fontWeight: "bold",
    fontSize: 18,
  },
  scoreText: {
    fontSize: 25,
    fontWeight: "bold",
    color: "#059669",
  },
  grid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    alignItems: "center",
    width: "90%",
    gap: 20,
  },
  shapeContainer: {
    width: 120,
    height: 120,
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
  },
  circleShape: {
    width: 120,
    height: 120,
    borderRadius: 60,
    margin: 12,
    backgroundColor: "#883dbeff",
    justifyContent: "center",
    alignItems: "center",
  },
  squareShape: {
    width: 110,
    height: 110,
    backgroundColor: "#d64747ff",
    margin: 12,
    justifyContent: "center",
    alignItems: "center",
  },

  triangleShape: {
    width: 0,
    height: 0,
    backgroundColor: "transparent",
    borderLeftWidth: 70,
    borderRightWidth: 70,
    borderBottomWidth: 110,
    margin: 12,
    gap: 5,
    borderLeftColor: "transparent",
    borderRightColor: "transparent",
    borderBottomColor: "#e1a91bff",
  },
  crossMark: {
    position: "absolute",
    fontSize: 60,
    color: "#ffffff",
    fontWeight: "900",
  },
  feedbackText: {
    fontSize: 50,
    fontWeight: "bold",
    color: "#FF5722",
    marginTop: 50,
    textAlign: "center",
  },
  rewardItem: {
    position: "absolute",
    top: 0,
    zIndex: 999,
  },

  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalContent: {
    width: "80%",
    backgroundColor: "#fff",
    borderRadius: 20,
    padding: 25,
    alignItems: "center",
    elevation: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
  },
  modalTitle: {
    fontSize: 30,
    fontWeight: "bold",
    marginBottom: 10,
    textAlign: "center",
  },
  modalMessage: {
    fontSize: 18,
    marginBottom: 20,
    textAlign: "center",
    marginTop: 20,
  },
  modalButtons: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: "100%",
  },
  modalButton: {
    flex: 1,
    backgroundColor: "#059669",
    paddingVertical: 12,
    marginHorizontal: 5,
    borderRadius: 10,
    alignItems: "center",
  },
  modalButtonText: {
    color: "#fff",
    fontWeight: "bold",
    fontSize: 16,
  },
  image: {
    width: 100,
    height: 100,
    resizeMode: "contain",
  },
});
